### ISSUE TITLE
Accuracy issue

### ISSUE THREAD

**Issue by sarthakpant772** [dsc-jiit-128/ML_classification_Hacktoberfest#2]
Try to get model accuracy above 96%
![image](https://user-images.githubusercontent.com/67951999/135218449-bb34fa81-90db-442d-9960-6d2286ede1bf.png)

**Comment by sarthakpant772** [comment]
Try changing some parameters of KNN so that it fits the data perfectly (warning: overfit may happen).

**Comment by void-02** [comment]
Hello,
I am willing to contribute on this issue.

**Comment by sarthakpant772** [comment]
@void-02  sure do it and please make you submission in submission folder.

**Comment by void-02** [comment]
Hello, 
Below are the accuracies which I got on different classifiers.
Should I add a new PR?

| Classifier | Accuracy |
|     :---:      |     :---:   |
| Random Forest | 98.12%  |
| Catboost   | 98.52%     |
| Multilayer Perceptron (MLP) | 98.16% |
| Light GBM | 98.83% |
| Bagged Decision Tree | 98.52% |
| Bagged Light GBM | 98.92%  |
|Bagged Catboost| 98.65% |

**Comment by sarthakpant772** [comment]
yes sure @void-02
