### ISSUE TITLE
getting best train test split value

### ISSUE THREAD

**Issue by sarthakpant772** [dsc-jiit-128/ML_classification_Hacktoberfest#4]
As of right now we are not able to split the data so that it increases the accuracy. We need u find the best ratio where the data can be split.

**Comment by sagnik1511** [comment]
Hello @sarthakpant772, I want to contribute to this issue #4 . Can you assign me on this?

**Comment by sarthakpant772** [comment]
@sagnik1511  yeh u r good to go
