### ISSUE TITLE
Documentation of data.

### ISSUE THREAD

**Issue by sarthakpant772** [dsc-jiit-128/ML_classification_Hacktoberfest#5]
Go thorugh the dataset and make a notebook which explain columns of our dataset (eg column37 display will a player wil or lose)

**Comment by nayan2306** [comment]
Can I do that I am beginner can you berif me once ?
Please assign me the work If you feel I am suitable?

**Comment by TishaJhabak1014** [comment]
@sarthakpant772 Hey, let me know if I can work on this.

**Comment by sarthakpant772** [comment]
Hey @nayan2306  you can work on this issue. What you can do is if u see ```data-description (kr-vs-kp).txt``` the description is not that much clear about data please go through ```King-RookvsKing-Pawn.xlsx``` and try to come up with good description of the data. All the best

**Comment by sarthakpant772** [comment]
Hey @TishaJhabak1014  sorry @nayan2306  asked it first. If u want to work on another issue let me know and if all are assigned why not create one of your own. Happy coding. 😄

**Comment by nayan2306** [comment]
Okay sure thanks
